INFO  | 06/24/2022 01:57:29 PM | File run_exp.py           | Line 26    | Writing log file to exp/GRAN/GRANMixtureBernoulli_social_2022-Jun-24-13-57-29_85511/log_exp_85511.txt
INFO  | 06/24/2022 01:57:29 PM | File run_exp.py           | Line 27    | Exp instance id = 85511
INFO  | 06/24/2022 01:57:29 PM | File run_exp.py           | Line 28    | Exp comment = None
INFO  | 06/24/2022 01:57:29 PM | File run_exp.py           | Line 29    | Config =
INFO  | 06/24/2022 01:57:36 PM | File gran_runner.py       | Line 135   | Train/val/test = 160/40/40
INFO  | 06/24/2022 01:57:37 PM | File gran_runner.py       | Line 148   | No Edges vs. Edges in training set = 89.22312601985614
ERROR | 06/24/2022 01:57:37 PM | File run_exp.py           | Line 46    | Traceback (most recent call last):
  File "/Users/alexdavies/Documents/Year_1/Project/GRAN_social/run_exp.py", line 40, in main
    runner.test()
  File "/Users/alexdavies/Documents/Year_1/Project/GRAN_social/runner/gran_runner.py", line 313, in test
    load_model(model, model_file, self.device)
  File "/Users/alexdavies/Documents/Year_1/Project/GRAN_social/utils/train_helper.py", line 48, in load_model
    model_snapshot = torch.load(file_name, map_location=device)
  File "/Users/alexdavies/miniforge3/envs/gran/lib/python3.9/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/alexdavies/miniforge3/envs/gran/lib/python3.9/site-packages/torch/serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/alexdavies/miniforge3/envs/gran/lib/python3.9/site-packages/torch/serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/alexdavies/Documents/Year_1/Project/GRAN_social/exp/GRAN/FACEBOOK/model_snapshot_0010000.pth'

